
/*Hàm thêm tài khoản nhân viên*/
CREATE PROC [dbo].[ADD_ACCOUNT]
@userName varchar(20), 
@passWord varchar(20),
@employee_id varchar(20)
AS
BEGIN
	INSERT INTO [dbo].ACCOUNT(USERNAME, PASS, EMPLOYEE_ID) 
	VALUES (@userName, @passWord, @employee_id) 
	SELECT * FROM dbo.ACCOUNT WHERE EMPLOYEE_ID = @employee_id
END
GO
--EXEC ADD_ACCOUNT @USERNAME='TEST', @PASSWORD = '123456', @EMPLOYEE_ID = 'NV04'


/*Hàm tạo mã phiếu thuê phòng tự động */
-- DROP FUNCTION[dbo].[AUTO_RENTBILL]
CREATE FUNCTION [dbo].[AUTO_RENTBILL]()
	RETURNS VARCHAR(20)
	AS
	BEGIN
    DECLARE @RENT_ID VARCHAR(20)
	DECLARE @COUNT INT 
	SELECT @COUNT = COUNT(RENT_ID) FROM RENT_BILL
	SET @RENT_ID = (SELECT	TOP (1) LEFT(RENT_ID,1) + CAST((RIGHT(RENT_ID,LEN(RENT_ID)-1)) + 1 AS VARCHAR(20))
	from RENT_BILL order by CAST(RIGHT(RENT_ID,LEN(RENT_ID)-1) AS INT) desc)
	RETURN isnull(@RENT_ID, 'R00')
END
--SELECT [dbo].[AUTO_RENTBILL]()  GO

/*Hàm THÊM PHIẾU ĐĂNG KÝ PHÒNG*/
--DROP PROC[dbo].[ADD_RENTBILL]
CREATE PROC [dbo].[ADD_RENTBILL]
@ROOM_ID VARCHAR(20),
@CUSTOMER_NAME NVARCHAR(50),
@CUSTOMER_ID VARCHAR(20)
AS
BEGIN
	DECLARE @RENT_ID VARCHAR(20)
	SET @RENT_ID = (SELECT [dbo].[AUTO_RENTBILL]())
	INSERT INTO RENT_BILL (RENT_ID, ROOM_ID,START_DATE, CUSTOMER_NAME, CUSTOMER_ID)
	VALUES (@RENT_ID, @ROOM_ID,GETDATE(), @CUSTOMER_NAME, @CUSTOMER_ID)
END
GO
--EXEC ADD_RENTBILL @ROOM_ID = 'P100', @CUSTOMER_NAME=N'Test Dữ liệu', @CUSTOMER_ID='KH012'

/*Hàm cập nhật tình trạng phòng*/
CREATE PROC [dbo].[update_room_status]
@room_id varchar(20)
AS
BEGIN
	declare @number_customer int
	set @number_customer = (SELECT COUNT(CUSTOMER_ID)
							FROM RENT_BILL
							WHERE ROOM_ID =@room_id)
	UPDATE ROOM
	SET STATUS = 1, CUSTOMER_NUMBERS = @number_customer
	WHERE ROOM_ID= @room_id
	SELECT * FROM dbo.ROOM WHERE ROOM_ID= @room_id
END
GO
/*Hàm kiểm tra khách hàng đã đăng ký*/
CREATE PROC [dbo].[check_customer]
@CMND INT
AS
BEGIN
SELECT COUNT(CUSTOMER_ID)
			FROM CUSTOMER
			WHERE ID_CARD = @CMND
END
GO

/*Hàm tạo mã khách hàng tự động */
--DROP FUNCTION [dbo].[AUTO_CUSTOMER]
CREATE FUNCTION [dbo].[AUTO_CUSTOMER]()
	RETURNS VARCHAR(20)
	AS
	BEGIN
    DECLARE @CUSTOMER_ID VARCHAR(20)
	DECLARE @COUNT INT 
	SELECT @COUNT = COUNT(CUSTOMER_ID) FROM CUSTOMER
	SET @CUSTOMER_ID = (SELECT	TOP (1) LEFT(CUSTOMER_ID,3) + CAST(RIGHT(CUSTOMER_ID,LEN(CUSTOMER_ID)-3) + 1 AS VARCHAR(20))
	from CUSTOMER order by CAST(RIGHT(CUSTOMER_ID,LEN(CUSTOMER_ID)-3)AS INT) desc)
	RETURN isnull(@CUSTOMER_ID, 'KH0')
END
GO
-- SELECT [dbo].[AUTO_CUSTOMER]()

/*Hàm tính số ngày thuê*/
--DROP FUNCTION [DBO].[RENT_DAY]
CREATE FUNCTION [DBO].[RENT_DAY]
(@ROOM_ID VARCHAR(20))
RETURNS INT
AS
BEGIN
	DECLARE @DAY_BEGIN DATETIME = (SELECT top(1) START_DATE FROM RENT_BILL WHERE ROOM_ID= @ROOM_ID ORDER BY START_DATE ASC)
	DECLARE @SONGAY INT =(SELECT DATEDIFF(day, @DAY_BEGIN, GETDATE()))
	RETURN ISNULL(@SONGAY,0)
END
GO
-- SELECT DBO.RENT_DAY('P102')

/*Hàm tính tiền thuê phòng*/
--DROP FUNCTION [DBO].[PAYMENT_BILL]
CREATE FUNCTION [DBO].[PAYMENT_BILL]
(@ROOM_ID VARCHAR(20), @SONGAY INT)
RETURNS FLOAT
AS
BEGIN
	DECLARE @DONGIA FLOAT = (SELECT PRICE FROM ROOM WHERE ROOM_ID=@ROOM_ID)
	DECLARE @SONGUOI INT = (SELECT COUNT(CUSTOMER_ID) FROM RENT_BILL WHERE ROOM_ID= @ROOM_ID)
	DECLARE @TONGTIEN FLOAT =0
	DECLARE @TYPE INT =(SELECT COUNT(CUSTOMER.CUSTOMER_ID) FROM CUSTOMER, RENT_BILL 
						WHERE CUSTOMER.TYPE_CUSTOMER=N'Nước ngoài' and RENT_BILL.ROOM_ID= @ROOM_ID AND CUSTOMER.CUSTOMER_ID = RENT_BILL.CUSTOMER_ID)
	IF (@SONGUOI <=2)
	BEGIN
		SET @TONGTIEN = @DONGIA * @SONGAY * @SONGUOI 
	END
	ELSE
	BEGIN
		SET @TONGTIEN = @DONGIA * @SONGAY * (2 + (@SONGUOI -2)*0.25)
	END
	IF(@TYPE >0)
	BEGIN
		SET @TONGTIEN = @TONGTIEN*1.5
	END
	RETURN @TONGTIEN
END
GO
--SELECT DBO.PAYMENT_BILL ('P103', (SELECT DBO.RENT_DAY('P103')))

/*Hàm tự động mã BILL_ID*/
--DROP FUNCTION [dbo].[AUTO_BILLID]
CREATE FUNCTION [dbo].[AUTO_BILLID]()
	RETURNS VARCHAR(20)
	AS
	BEGIN
    DECLARE @BILL_ID VARCHAR(20)
	DECLARE @COUNT INT 
	SELECT @COUNT = COUNT(BILL_ID) FROM BILL
	SET @BILL_ID = (SELECT	TOP (1) LEFT(BILL_ID,3) + CAST(RIGHT(BILL_ID,LEN(BILL_ID)-3) + 1 AS VARCHAR(20))
	from BILL order by CAST(RIGHT(BILL_ID,LEN(BILL_ID)-3) AS INT) desc)
	RETURN isnull(@BILL_ID, 'B001')
END
GO
--SELECT DBO.AUTO_BILLID()

/*Hàm tự động mã BILL_INFO_ID*/
--DROP FUNCTION [dbo].[AUTO_BILL_INFO_ID]
CREATE FUNCTION [dbo].[AUTO_BILL_INFO_ID]()
	RETURNS VARCHAR(20)
	AS
	BEGIN
    DECLARE @BILL_INFO_ID VARCHAR(20)
	DECLARE @COUNT INT 
	SELECT @COUNT = COUNT(BILL_INFO_ID) FROM BILL_INFO
	SET @BILL_INFO_ID = (SELECT	TOP (1) LEFT(BILL_INFO_ID,3) + CAST(RIGHT(BILL_INFO_ID,LEN(BILL_INFO_ID)-3) + 1 AS VARCHAR(20))
	from BILL_INFO order by CAST(RIGHT(BILL_INFO_ID,LEN(BILL_INFO_ID)-3) AS INT) desc)
	RETURN isnull(@BILL_INFO_ID, 'BI01')
END
GO
--SELECT DBO.AUTO_BILL_INFO_ID()

--DROP PROC [DBO].[INSERT_BILL]
CREATE PROC [DBO].[INSERT_BILL]
@ROOM_ID VARCHAR(20), @CUSTOMER_NAME NVARCHAR(50)
AS
BEGIN
	DECLARE @DAY_BEGIN DATETIME = (SELECT top(1) START_DATE FROM RENT_BILL WHERE ROOM_ID= @ROOM_ID ORDER BY START_DATE ASC)
	DECLARE @SONGAY INT =(SELECT DATEDIFF(day, @DAY_BEGIN, GETDATE()))
	DECLARE @BILL_ID VARCHAR(20) =(SELECT DBO.AUTO_BILLID())
	DECLARE @CUSTOMER_ID VARCHAR(20) = (SELECT TOP(1) CUSTOMER_ID FROM RENT_BILL WHERE ROOM_ID= @ROOM_ID AND CUSTOMER_NAME LIKE '%'+ @CUSTOMER_NAME +'%' ) 
	DECLARE @TOTAL_BILL FLOAT = (SELECT DBO.PAYMENT_BILL (@ROOM_ID, @SONGAY))
	--THÊM BILL
	INSERT INTO BILL (BILL_ID,ROOM_ID,CUSTOMER_ID,DATE_NUMBERS,TOTALBILL)
	VALUES (@BILL_ID, @ROOM_ID, @CUSTOMER_ID, @SONGAY, @TOTAL_BILL)
	-- THÊM BILL_INFO
	DECLARE @BILL_INFO_ID VARCHAR(20) =(SELECT DBO.AUTO_BILL_INFO_ID())
	SET @CUSTOMER_NAME = (SELECT TOP(1)CUSTOMER_NAME FROM RENT_BILL WHERE ROOM_ID=@ROOM_ID AND CUSTOMER_ID= @CUSTOMER_ID)
	DECLARE @ADDRESS NVARCHAR(50) = (SELECT TOP(1) CUSTOMER.ADDRESS FROM CUSTOMER, RENT_BILL WHERE CUSTOMER.CUSTOMER_ID = RENT_BILL.CUSTOMER_ID AND RENT_BILL.ROOM_ID = @ROOM_ID)
	DECLARE @DONGIA FLOAT = (SELECT PRICE FROM ROOM WHERE ROOM_ID=@ROOM_ID)
	INSERT INTO BILL_INFO( BILL_INFO_ID,BILL_ID,ROOM_ID,CUSTOMER_ID,CUSTOMER_NAME,ADDRESS,VALUE_PRICE,PRICE,PAY_DAY,MONEY)
	VALUES	(@BILL_INFO_ID, @BILL_ID, @ROOM_ID, @CUSTOMER_ID, @CUSTOMER_NAME, @ADDRESS, @TOTAL_BILL, @DONGIA, GETDATE(), @TOTAL_BILL)

END
GO
--EXEC INSERT_BILL @ROOM_ID ='P108', @CUSTOMER_NAME = 'OANH'

CREATE PROC [DBO].[CHECKOUT_ROOM]
@ROOM_ID VARCHAR(20)
AS
BEGIN
	--CẬP NHẬT PHÒNG
	UPDATE ROOM
	SET STATUS = 0, CUSTOMER_NUMBERS = 0
	WHERE ROOM_ID= @room_id
	--XÓA THÔNG TIN PHIẾU THUÊ
	DELETE FROM RENT_BILL
	WHERE ROOM_ID = @ROOM_ID
END
GO
--EXEC CHECKOUT_ROOM @ROOM_ID ='P105' 

--DROP PROC [DBO].[THANHTOAN]
CREATE PROC [DBO].[THANHTOAN]
@ROOM_ID VARCHAR(20), @CUSTOMER_NAME NVARCHAR(50)
AS
BEGIN
EXEC INSERT_BILL @ROOM_ID =@ROOM_ID, @CUSTOMER_NAME = @CUSTOMER_NAME
EXEC CHECKOUT_ROOM @ROOM_ID =@ROOM_ID
END
GO

--EXEC THANHTOAN @ROOM_ID ='P101', @CUSTOMER_NAME = N'Test Dữ liệu'